assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/



exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

ga_analytics: UA-XXXXXXXX-X

gems:
  - jekyll-assets
  - jekyll-sitemap

# Build settings
markdown: kramdown

# Site settings
title: Learn Kickster

name: learn_kickster

permalink: pretty

baseurl: 
url: http://fbs70.github.io
